version: "2"
linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: the "Default" linters https://golangci-lint.run/docs/linters/#all-linters
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: all
  # Enable specific linter.
  # enable:
  #   - arangolint
  # Disable specific linters.
  disable:
    - depguard
    - exhaustruct
    - mnd
    - nonamedreturns
    - varnamelen
    - wsl
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
